#!/usr/bin/env php
<?php
/*
 * foxverse Topia
 * Handles console interaction.
 */

namespace Miiverse;

use Symfony\Component\Console\Application;;

require_once 'core.php';

$application = new Application(config('general.name'));

// Declare commands
$application->add(new Console\Command\DatabaseInstallCommand);
$application->add(new Console\Command\DatabaseMigrateCommand);
$application->add(new Console\Command\DatabaseResetCommand);
$application->add(new Console\Command\DatabaseRollbackCommand);
$application->add(new Console\Command\DatabaseStatusCommand);

$application->add(new Console\Command\ChangeDisplayNameCommand);

$application->add(new Console\Command\ServeCommand);

$application->add(new Console\Command\SetupCommand);

$application->add(new Console\Command\JavascriptBuilderCommand);

// Run the application
$application->run();